name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Tag: $TAG_NAME, Version: $VERSION"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Update version in manifest
        run: |
          npm install -g jq
          jq ".version = \"${{ steps.get_version.outputs.version }}\"" manifest.json > manifest.json.tmp
          mv manifest.json.tmp manifest.json
          echo "Updated manifest.json version to ${{ steps.get_version.outputs.version }}"

      - name: Update versions.json
        run: |
          export npm_package_version=${{ steps.get_version.outputs.version }}
          node version-bump.mjs

      - name: Build
        run: npm run build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "${{ steps.get_version.outputs.version }}"
          files: |
            dist/main.js
            manifest.json
            styles.css
            versions.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
